CREATE TABLE IF NOT EXISTS game_scoring_links (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id integer NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  created_by integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  operator_label varchar(120) NOT NULL,
  operator_name varchar(120),
  token_hash char(64) NOT NULL UNIQUE,
  pin_hash varchar(255) NOT NULL,
  expires_at timestamp NOT NULL,
  last_used_at timestamp,
  revoked_at timestamp,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS game_scoring_links_match_active_idx ON game_scoring_links(match_id,expires_at,revoked_at);
