import { useEffect,useMemo,useState } from 'react';
import tournamentService from '../services/tournamentService';
import gameDayService from '../services/gameDayService';
import { useAuth } from '../hooks/useAuth';
import LoadingSpinner from '../components/LoadingSpinner';
import '../styles/game-day-operations.css';
import '../styles/game-day-polish.css';

const checks=[['venue_ready','Venue & court'],['equipment_ready','Equipment'],['home_team_present','Home team'],['away_team_present','Away team'],['lineups_confirmed','Starting lineups'],['officials_ready','Statistician'],['medical_ready','First aid']];
const blankIncident={incident_type:'injury',severity:'low',description:'',action_taken:''};
const isChecked=value=>value===true||value===1||value==='1';
export default function GameDayOperations(){
 const{user}=useAuth(),isAdmin=['platform_admin','admin'].includes(user?.role);
 const[tournaments,setTournaments]=useState([]),[tournamentId,setTournamentId]=useState(''),[games,setGames]=useState([]),[incidents,setIncidents]=useState([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[incidentMatch,setIncidentMatch]=useState(null),[incident,setIncident]=useState(blankIncident),[message,setMessage]=useState(null),[saving,setSaving]=useState(false);
 const load=async(id=tournamentId)=>{if(!id)return;setLoading(true);try{const data=await gameDayService.overview(id);setGames(data.games||[]);setIncidents(data.incidents||[]);}catch(e){setMessage({type:'danger',text:e.response?.data?.message||'Unable to load game-day operations.'});}finally{setLoading(false);}};
 useEffect(()=>{tournamentService.getTournaments().then(data=>{const rows=data.tournaments||[];setTournaments(rows);if(rows[0])setTournamentId(String(rows[0].id));});},[]);
 useEffect(()=>{if(tournamentId)load(tournamentId);},[tournamentId]);
 const summary=useMemo(()=>({ready:games.filter(g=>checks.every(([key])=>isChecked(g[key]))).length,attention:games.filter(g=>!checks.every(([key])=>isChecked(g[key]))).length,live:games.filter(g=>g.status==='in_progress').length,open:incidents.filter(i=>i.status==='open').length}),[games,incidents]);
 const save=async()=>{setSaving(true);try{await gameDayService.saveReadiness(selected.id,selected);setMessage({type:'success',text:'Game readiness saved.'});setSelected(null);await load();}catch(e){setMessage({type:'danger',text:e.response?.data?.message||'Unable to save readiness.'});}finally{setSaving(false);}};
 const report=async()=>{setSaving(true);try{await gameDayService.reportIncident(incidentMatch.id,incident);setMessage({type:'success',text:'Incident report saved.'});setIncidentMatch(null);setIncident(blankIncident);await load();}catch(e){setMessage({type:'danger',text:e.response?.data?.message||'Unable to save incident.'});}finally{setSaving(false);}};
 const resolve=async id=>{setSaving(true);try{await gameDayService.resolveIncident(id);setMessage({type:'success',text:'Incident marked as resolved.'});await load();}catch(e){setMessage({type:'danger',text:e.response?.data?.message||'Unable to resolve this incident.'});}finally{setSaving(false);}};
 return <div className="container-fluid p-0 game-day-page">
  <header className="game-day-hero"><div className="game-day-hero-copy"><span>COURTSIDE COMMAND · GAME OPERATIONS</span><h1>Game-Day Readiness<br/><em>&amp; Incident Desk</em></h1><p>One courtside view for pregame checks, live operations, and incident follow-up.</p></div><label className="game-day-tournament"><span>Active competition</span><select aria-label="Select tournament for game-day operations" value={tournamentId} onChange={e=>setTournamentId(e.target.value)}>{tournaments.length?tournaments.map(t=><option value={t.id} key={t.id}>{t.name}</option>):<option value="">No tournaments available</option>}</select></label></header>
  {message&&<div className={`alert alert-${message.type}`}>{message.text}<button className="btn-close float-end" onClick={()=>setMessage(null)}/></div>}
  <section className="game-day-stats"><article><i className="bi bi-check2-circle"/><div><small>Game ready</small><strong>{summary.ready}</strong></div></article><article><i className="bi bi-exclamation-diamond"/><div><small>Needs attention</small><strong>{summary.attention}</strong></div></article><article><i className="bi bi-broadcast-pin"/><div><small>Live games</small><strong>{summary.live}</strong></div></article><article><i className="bi bi-shield-exclamation"/><div><small>Open incidents</small><strong>{summary.open}</strong></div></article></section>
  {isAdmin&&<div className="game-day-notice"><i className="bi bi-eye-fill"/><div><b>Administrator oversight</b><span>Organizers complete checklists and incident reports. Administrator access is monitoring-only.</span></div></div>}
  {loading?<LoadingSpinner message="Loading game-day operations..."/>:<><section className="game-day-section"><div className="game-day-section-head"><div><span>PRE-GAME CHECKS</span><h2>Today’s court readiness</h2><p>Seven checks help each game start safely and on time.</p></div><span className="game-day-section-count"><i className="bi bi-calendar2-week"/>{games.length} {games.length===1?'game':'games'}</span></div><div className="game-day-grid">{games.map(game=>{const done=checks.filter(([key])=>isChecked(game[key])).length,ready=done===checks.length;return <article className="game-day-card" key={game.id}><div className="game-day-card-top"><span className={`game-ready-pill ${ready?'ready':'pending'}`}><i className={`bi ${ready?'bi-check-circle-fill':'bi-hourglass-split'}`}/>{ready?'READY':`${done}/${checks.length} READY`}</span><span>{game.stage_name||`Round ${game.round_number}`}</span></div><h3>{game.home_team||'TBD'} <em>vs</em> {game.away_team||'TBD'}</h3><p><i className="bi bi-calendar3"/> {game.scheduled_start_time?new Date(game.scheduled_start_time).toLocaleString():'Schedule pending'}</p><p><i className="bi bi-geo-alt"/> {game.court_name||game.venue_name||'Court TBA'}</p><div className="game-check-progress"><div><span>Readiness checklist</span><b>{done}/{checks.length}</b></div><span className="game-check-track"><i style={{width:`${Math.round(done/checks.length*100)}%`}}/></span></div><div className="game-check-dots">{checks.map(([key,label])=><span className={isChecked(game[key])?'done':''} title={label} aria-label={`${label}: ${isChecked(game[key])?'ready':'not checked'}`} key={key}><i className={`bi ${isChecked(game[key])?'bi-check2':'bi-dash'}`}/><small>{label}</small></span>)}</div><div className="game-day-actions">{!isAdmin&&<button onClick={()=>setSelected({...game})}><i className="bi bi-clipboard2-check"/> Readiness</button>}<button className="incident" onClick={()=>setIncidentMatch(game)}><i className="bi bi-shield-exclamation"/> {isAdmin?'View incidents':'Report incident'}</button>{Number(game.open_incidents)>0&&<b>{game.open_incidents} open</b>}</div></article>})}{!games.length&&<div className="ops-empty"><i className="bi bi-calendar-x"/><strong>No games scheduled yet</strong><p>Once the organizer publishes a schedule, court readiness and incident tools will appear here.</p></div>}</div></section>
  <section className="incident-panel"><div className="incident-head"><div><span>INCIDENT REGISTER · RESTRICTED OPERATIONS LOG</span><h2>Reports &amp; resolutions</h2><p>Document an issue, immediate response, and follow-up status.</p></div><b><i className="bi bi-exclamation-circle"/>{summary.open} open</b></div>{incidents.map(row=><article key={row.id}><span className={`incident-severity ${row.severity}`}><i className={`bi ${row.incident_type==='injury'?'bi-bandaid':row.incident_type==='security'?'bi-shield-lock':row.incident_type==='venue'?'bi-geo-alt':'bi-exclamation-triangle'}`}/>{row.severity}</span><div><b>{row.incident_type} · {row.home_team||'TBD'} vs {row.away_team||'TBD'}</b><p>{row.description}</p><small>{new Date(row.created_at).toLocaleString()} · {row.reported_by_name||'Organizer'}{row.action_taken?` · Action: ${row.action_taken}`:''}</small></div><span className={`incident-status ${row.status}`}>{row.status==='open'?'Needs follow-up':'Resolved'}</span>{!isAdmin&&row.status==='open'&&<button disabled={saving} onClick={()=>resolve(row.id)}>Resolve</button>}</article>)}{!incidents.length&&<div className="game-day-empty"><i className="bi bi-shield-check"/><div><b>No incidents reported</b><span>All clear. New game-day incident records will appear here.</span></div></div>}</section></>}
  {selected&&<div className="modal show d-block game-modal"><div className="modal-dialog modal-dialog-centered"><div className="modal-content"><header><div><span>PREGAME CHECKLIST</span><h5>{selected.home_team} vs {selected.away_team}</h5></div><button className="btn-close" onClick={()=>setSelected(null)}/></header><div className="modal-body game-checklist">{checks.map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(selected[key])} onChange={e=>setSelected({...selected,[key]:e.target.checked})}/><i className={`bi ${selected[key]?'bi-check-circle-fill':'bi-circle'}`}/><span>{label}</span></label>)}<label className="notes"><span>Operations notes</span><textarea rows="3" value={selected.notes||''} onChange={e=>setSelected({...selected,notes:e.target.value})} placeholder="Delays, unavailable equipment, or special instructions"/></label></div><footer><button onClick={()=>setSelected(null)}>Cancel</button><button className="primary" disabled={saving} onClick={save}>{saving?'Saving…':'Save readiness'}</button></footer></div></div></div>}
  {incidentMatch&&<div className="modal show d-block game-modal"><div className="modal-dialog modal-dialog-centered"><div className="modal-content"><header><div><span>INCIDENT REPORT</span><h5>{incidentMatch.home_team} vs {incidentMatch.away_team}</h5></div><button className="btn-close" onClick={()=>setIncidentMatch(null)}/></header>{isAdmin?<div className="modal-body"><p className="text-muted mb-0">Use the incident register below to monitor reports. Organizers create and resolve operational incidents.</p></div>:<div className="modal-body incident-form"><label>Incident type<select value={incident.incident_type} onChange={e=>setIncident({...incident,incident_type:e.target.value})}><option value="injury">Injury</option><option value="misconduct">Misconduct</option><option value="technical">Technical</option><option value="venue">Venue</option><option value="security">Security</option><option value="other">Other</option></select></label><label>Severity<select value={incident.severity} onChange={e=>setIncident({...incident,severity:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label className="wide">Description<textarea required rows="3" value={incident.description} onChange={e=>setIncident({...incident,description:e.target.value})}/></label><label className="wide">Immediate action taken<textarea rows="2" value={incident.action_taken} onChange={e=>setIncident({...incident,action_taken:e.target.value})}/></label></div>}<footer><button onClick={()=>setIncidentMatch(null)}>Close</button>{!isAdmin&&<button className="danger" disabled={saving||!incident.description.trim()} onClick={report}>{saving?'Saving…':'Submit report'}</button>}</footer></div></div></div>}
 </div>;
}
