import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import contentService from '../services/contentService';
import { CourtNav, CourtFooter, CourtEmpty, MatchCard, TournamentCard } from '../components/PublicCourt';
import { useCourtData } from '../hooks/useCourtData';
import courtDate from '../utils/courtDate';
export default function Home() {
  const { data, loading, error, retry } = useCourtData();
  const [news, setNews] = useState([]), [announcements, setAnnouncements] = useState([]);
  useEffect(() => { let active=true; contentService.getNews().then(items=>{if(active)setNews(items);}).catch(()=>{});contentService.getAnnouncements().then(items=>{if(active)setAnnouncements(items);}).catch(()=>{});return()=>{active=false;}; }, []);
  const featured = [...data.matches].sort((a,b)=>(a.status==='in_progress'?-1:1)-(b.status==='in_progress'?-1:1)).slice(0,3);
  return <div className="court-site court-home-dark">
    <div className="court-home-top"><CourtNav/><main className="court-container court-hero"><div className="court-hero-copy"><span className="court-kicker">For the love of the game</span><h1>YOUR COURT.<br/>YOUR GAME.<br/><em>YOUR MOMENT.</em></h1><p>From the opening tip to the final buzzer. Follow the action, find your team, and be part of the basketball community.</p><div className="court-hero-actions"><Link to="/sports" className="court-button">Explore the games <i className="bi bi-arrow-up-right"/></Link><Link to="/register" className="court-button outline">Join FullCourt</Link></div><div className="court-hero-note"><i className="bi bi-broadcast"/><span>Scores, schedules, and standings. Open to everyone.</span></div></div><figure className="court-hero-art"><img src="/kadayo-profile-edited.png" alt="KA-DAYO metallic black and red emblem with silver wordmark" width="1254" height="1254"/><span className="court-art-stamp">BUILT FOR BASKETBALL.</span><figcaption><span>KA-DAYO NATION</span><span>COMMUNITY SPOTLIGHT ↗</span></figcaption></figure></main></div>
    <div className="court-ribbon"><span>ONE PASSION</span><i className="bi bi-dribbble"/><span>EVERY COURT</span><i className="bi bi-dribbble"/><span>ONE COMMUNITY</span></div>
    <section className="court-container court-section"><div className="court-section-heading"><div><span className="court-kicker">Around the league</span><h2>The action starts here.</h2></div><Link className="court-text-link" to="/sports">All games →</Link></div>{error&&<div role="alert" className="court-error">{error}<button onClick={retry}>Try again</button></div>}<div className="court-grid">{loading?<CourtEmpty>Loading game updates…</CourtEmpty>:featured.length?featured.map(match=><MatchCard key={match.id} match={match}/>):!error&&<CourtEmpty>No published games yet. Check back for the next tip-off.</CourtEmpty>}</div></section>
    <section className="court-container court-section" style={{paddingTop:0}}><div className="court-section-heading"><div><span className="court-kicker">Find your competition</span><h2>More than a matchup.</h2></div><Link className="court-text-link" to="/sports">Explore tournaments →</Link></div><div className="court-grid">{loading?<CourtEmpty>Loading tournaments…</CourtEmpty>:data.tournaments.length?data.tournaments.slice(0,3).map((tournament,index)=><TournamentCard key={tournament.id} tournament={tournament} index={index}/>):!error&&<CourtEmpty>Tournament announcements will appear here once published.</CourtEmpty>}</div></section>
    <section className="court-container court-section" style={{paddingTop:0}}><div className="court-home-community"><div><span className="court-kicker">Ka-DAYO • Basketball community</span><h2>Big moments.<br/>Stronger connections.</h2><p>A place for players to compete, coaches to build their teams, and organizers to bring the community together.</p><Link to="/register" className="court-button">Be part of the game ↗</Link></div><div className="court-feature-list">{[['bi-people','For the players','Your team, your schedule, your performance. Stay connected to every game.'],['bi-clipboard2-pulse','For the coaches','Bring your roster together and prepare for the next matchup.'],['bi-trophy','For the organizers','Keep competitions, schedules, and results in one place.']].map(([icon,title,copy])=><article key={title}><i className={'bi '+icon}/><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>
    {(announcements.length>0||news.length>0)&&<section className="court-container court-section" style={{paddingTop:0}}><div className="court-section-heading"><div><span className="court-kicker">Off the court</span><h2>From the community.</h2></div></div><div className="court-grid">{announcements.map(item=><article key={'a'+item.id} className="court-news-card"><span className="court-status">{item.priority||'Announcement'}</span><h3>{item.title}</h3><p>{item.message}</p><small>{courtDate(item.published_at)}</small></article>)}{news.map(item=><article key={'n'+item.id} className="court-news-card"><span className="court-status">{item.sport_name||'Basketball news'}</span><h3>{item.title}</h3><p>{item.summary}</p><small>{courtDate(item.published_at)}</small></article>)}</div></section>}
    <CourtFooter/>
  </div>;
}
