import {useEffect,useRef,useState} from 'react';
import eligibilityService from '../services/eligibilityService';
import LoadingSpinner from '../components/LoadingSpinner';

const badge=s=>s==='verified'?'bg-success':s==='rejected'?'bg-danger':'bg-warning text-dark';
export default function PlayerDocuments(){
 const[membership,setMembership]=useState(null),[documents,setDocuments]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const[idFile,setIdFile]=useState(null),[selfie,setSelfie]=useState(null),[idType,setIdType]=useState('School ID'),[last4,setLast4]=useState(''),[idBirthDate,setIdBirthDate]=useState(''),[consent,setConsent]=useState(false),[submitting,setSubmitting]=useState(false),[cameraOn,setCameraOn]=useState(false);
 const videoRef=useRef(null),canvasRef=useRef(null),streamRef=useRef(null);
 const load=async()=>{const r=await eligibilityService.getMyMembership();setMembership(r.membership);if(r.membership)setDocuments(await eligibilityService.documents(r.membership.id));};
 useEffect(()=>{load().finally(()=>setLoading(false));return()=>streamRef.current?.getTracks().forEach(t=>t.stop());},[]);
 const startCamera=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});streamRef.current=stream;setCameraOn(true);setTimeout(()=>{if(videoRef.current)videoRef.current.srcObject=stream;});}catch{setMessage('Camera access was blocked. Allow camera permission and try again.');}};
 const capture=()=>{const v=videoRef.current,c=canvasRef.current;if(!v||!c)return;c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);c.toBlob(b=>b&&setSelfie(new File([b],'live-selfie.jpg',{type:'image/jpeg'})),'image/jpeg',.9);streamRef.current?.getTracks().forEach(t=>t.stop());setCameraOn(false);};
 const submit=async()=>{setSubmitting(true);setMessage('');try{const r=await eligibilityService.uploadIdentity(membership.id,{idType,last4,idBirthDate,idFile,selfie,consent});await load();setIdFile(null);setSelfie(null);setLast4('');setConsent(false);setMessage(r.data?.birthdate_match?'Identity submitted. The ID birthdate matches your profile.':'Identity submitted. A reviewer must check the birthdate or identity details.');}catch(e){setMessage(e.response?.data?.message||'Identity submission failed.');}finally{setSubmitting(false);}};
 if(loading)return <LoadingSpinner message="Loading identity verification..."/>;
 return <div className="container-fluid p-0" style={{maxWidth:1050}}><div className="mb-4"><h3 className="fw-bold mb-1"><i className="bi bi-person-vcard-fill text-evsu-primary me-2"/>Identity &amp; Age Verification</h3><p className="text-muted">Submit a valid ID and a live selfie. Only authorized reviewers can access these private files.</p></div>{message&&<div className="alert alert-info">{message}</div>}
 {!membership?<div className="card-custom p-5 text-center"><i className="bi bi-people fs-1 text-muted"/><h5 className="mt-3">No team invitation yet</h5><p className="text-muted mb-0">Accept a team invitation before submitting verification.</p></div>:<><div className="card-custom p-4 mb-4"><div className="d-flex justify-content-between flex-wrap gap-2 mb-3"><div><span className="badge bg-dark mb-2">PRIVATE REVIEW</span><h5 className="fw-bold mb-1">Government or School ID</h5><small className="text-muted">Only the last four ID characters are stored as searchable text.</small></div><span className={`badge align-self-start ${badge(membership.eligibility_status)}`}>{membership.eligibility_status}</span></div><div className="row g-3">
 <div className="col-md-6"><label className="form-label fw-semibold">ID Type</label><select className="form-select" value={idType} onChange={e=>setIdType(e.target.value)}>{['School ID','National ID','Passport',"Driver's License",'Barangay ID','Other Government ID'].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="col-md-6"><label className="form-label fw-semibold">Last 4 characters of ID</label><input className="form-control text-uppercase" maxLength="4" value={last4} onChange={e=>setLast4(e.target.value.replace(/[^a-z0-9]/gi,''))} placeholder="Example: 1234"/></div>
 <div className="col-md-6"><label className="form-label fw-semibold">Birthdate shown on ID</label><input type="date" className="form-control" value={idBirthDate} max={new Date().toISOString().slice(0,10)} onChange={e=>setIdBirthDate(e.target.value)}/></div>
 <div className="col-md-6"><label className="form-label fw-semibold">Clear photo of ID</label><input type="file" accept="image/jpeg,image/png" className="form-control" onChange={e=>setIdFile(e.target.files?.[0]||null)}/></div>
 <div className="col-12"><div className="border rounded-4 p-3 bg-body-tertiary"><div className="d-flex justify-content-between align-items-center flex-wrap gap-2"><div><b>Live selfie</b><small className="d-block text-muted">Use good lighting and remove masks or filters.</small></div>{!cameraOn&&!selfie&&<button className="btn btn-outline-danger" onClick={startCamera}><i className="bi bi-camera-fill me-2"/>Open Camera</button>}{selfie&&<button className="btn btn-outline-secondary" onClick={()=>setSelfie(null)}>Retake</button>}</div>{cameraOn&&<div className="text-center mt-3"><video ref={videoRef} autoPlay playsInline muted className="rounded-3 w-100" style={{maxHeight:360,objectFit:'cover'}}/><button className="btn btn-danger mt-2" onClick={capture}>Capture Selfie</button></div>}{selfie&&<div className="alert alert-success py-2 mt-3 mb-0"><i className="bi bi-check-circle-fill me-2"/>Live selfie captured.</div>}<canvas ref={canvasRef} hidden/></div></div>
 <div className="col-12"><label className="d-flex gap-2 align-items-start"><input type="checkbox" className="form-check-input mt-1" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span className="small">I consent to the restricted use of my ID and selfie for identity and age verification. The final decision is made by an authorized reviewer.</span></label></div>
 <div className="col-12"><button className="btn btn-evsu px-4" disabled={submitting||!idFile||!selfie||!idBirthDate||last4.length!==4||!consent} onClick={submit}>{submitting?'Submitting…':'Submit for Review'}</button></div></div></div>
 <div className="card-custom p-4"><h5 className="fw-bold">Submission History</h5>{documents.map(d=><div className="d-flex justify-content-between align-items-center border-bottom py-3" key={d.id}><div><b>{d.document_type}</b>{d.id_type&&<small className="d-block text-muted">{d.id_type} • ID ending in ••••{d.id_number_last4}</small>}<small className="d-block text-muted">Submitted {new Date(d.created_at).toLocaleDateString()}</small>{d.birthdate_match!==null&&<small className={d.birthdate_match?'text-success':'text-danger'}>{d.birthdate_match?'Birthdate matched automatically':'Birthdate mismatch—manual review required'}</small>}{d.review_notes&&<small className="d-block text-danger">{d.review_notes}</small>}</div><span className={`badge ${badge(d.status)}`}>{d.status}</span></div>)}{!documents.length&&<p className="text-muted mb-0">No identity submission yet.</p>}</div></>}</div>;
}
