import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {CourtEmpty,CourtFooter,CourtNav,CourtStatus} from '../components/PublicCourt';
import publicService from '../services/publicService';
import '../styles/daily-schedule.css';

const isoDate=value=>value?String(value).slice(0,10):'';
const localToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const shift=(value,days)=>{const d=new Date(`${value}T00:00:00`);d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const time=value=>value?new Date(String(value).replace(' ','T')).toLocaleTimeString('en-PH',{hour:'numeric',minute:'2-digit'}):'TBA';
const dayLabel=value=>new Date(`${value}T00:00:00`).toLocaleDateString('en-PH',{weekday:'long',month:'long',day:'numeric',year:'numeric'});

export default function PublicDailySchedule(){
 const[games,setGames]=useState([]),[date,setDate]=useState(localToday()),[status,setStatus]=useState('all'),[query,setQuery]=useState(''),[tournament,setTournament]=useState('all'),[venue,setVenue]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=()=>{setLoading(true);publicService.getDailySchedule().then(setGames).then(()=>setError('')).catch(()=>setError('The public schedule is temporarily unavailable.')).finally(()=>setLoading(false));};
 useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer);},[]);
 const tournaments=useMemo(()=>[...new Map(games.map(g=>[String(g.tournament_id),g.tournament_name])).entries()],[games]);
 const venues=useMemo(()=>[...new Set(games.map(g=>g.venue_name).filter(Boolean))].sort(),[games]);
 const visible=useMemo(()=>games.filter(g=>{const live=['in_progress','halftime'].includes(g.status),finished=['completed','final'].includes(g.status),upcoming=!live&&!finished&&!['cancelled','postponed'].includes(g.status);const statusOk=status==='all'||status==='live'&&live||status==='final'&&finished||status==='upcoming'&&upcoming;const hay=[g.tournament_name,g.team1_name,g.team2_name,g.stage_name,g.court_name,g.venue_name].filter(Boolean).join(' ').toLowerCase();return isoDate(g.scheduled_start_time)===date&&statusOk&&(tournament==='all'||String(g.tournament_id)===tournament)&&(venue==='all'||g.venue_name===venue)&&hay.includes(query.trim().toLowerCase());}),[games,date,status,query,tournament,venue]);
 const counts={live:visible.filter(g=>['in_progress','halftime'].includes(g.status)).length,final:visible.filter(g=>['completed','final'].includes(g.status)).length,total:visible.length};
 return <div className="court-site daily-site"><CourtNav/><header className="daily-hero"><div className="court-container"><span className="court-kicker">FullCourt / Official schedule</span><div><h1>Daily games.</h1><p>One place for every published basketball matchup, live score, court, and final result.</p><div className="daily-pulse"><i/> Refreshes every 30 seconds</div></div></div></header><main className="court-container daily-main"><section className="daily-datebar"><button onClick={()=>setDate(shift(date,-1))} aria-label="Previous day"><i className="bi bi-chevron-left"/></button><div><small>SELECTED DATE</small><strong>{dayLabel(date)}</strong><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><button onClick={()=>setDate(shift(date,1))} aria-label="Next day"><i className="bi bi-chevron-right"/></button><button className="daily-today" onClick={()=>setDate(localToday())}>Today</button></section>
  <section className="daily-summary"><div><b>{counts.total}</b><span>Games</span></div><div className="live"><b>{counts.live}</b><span>Live now</span></div><div><b>{counts.final}</b><span>Final</span></div></section>
  <section className="daily-tools"><label><i className="bi bi-search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search team, stage, court, or venue"/></label><select value={tournament} onChange={e=>setTournament(e.target.value)}><option value="all">All tournaments</option>{tournaments.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select><select value={venue} onChange={e=>setVenue(e.target.value)}><option value="all">All venues</option>{venues.map(v=><option key={v}>{v}</option>)}</select></section>
  <div className="daily-filters">{[['all','All games'],['live','Live'],['upcoming','Upcoming'],['final','Final']].map(([key,label])=><button className={status===key?'active':''} onClick={()=>setStatus(key)} key={key}>{label}</button>)}</div>
  {error&&<div className="court-error">{error}<button onClick={load}>Try again</button></div>}{loading?<CourtEmpty>Loading the official schedule…</CourtEmpty>:visible.length?<section className="daily-list">{visible.map(g=>{const showScore=['in_progress','halftime','completed','final'].includes(g.status);return <article className={['in_progress','halftime'].includes(g.status)?'live':''} key={g.id}><div className="daily-time"><b>{time(g.scheduled_start_time)}</b><small>{g.stage_name||`Game ${g.match_number||g.id}`}</small></div><div className="daily-game"><div className="daily-game-head"><Link to={`/sports/tournaments/${g.tournament_id}`}>{g.tournament_name}</Link><CourtStatus status={g.status}/></div><div className="daily-teams"><span><i>{(g.team1_name||'TBD').slice(0,2).toUpperCase()}</i><b>{g.team1_name||'To be determined'}</b><strong>{showScore?g.team1_score:'–'}</strong></span><span><i>{(g.team2_name||'TBD').slice(0,2).toUpperCase()}</i><b>{g.team2_name||'To be determined'}</b><strong>{showScore?g.team2_score:'–'}</strong></span></div></div><div className="daily-place"><span><i className="bi bi-geo-alt"/>{g.venue_name||'Venue TBA'}</span><small>{g.court_name||'Court TBA'}</small><Link to={`/sports/games/${g.id}?tournament=${g.tournament_id}`}>{['in_progress','halftime'].includes(g.status)?'Watch live':'Game details'} <i className="bi bi-arrow-up-right"/></Link></div></article>})}</section>:<CourtEmpty>No games match this date and filter. Try another date or choose All games.</CourtEmpty>}
 </main><CourtFooter/></div>;
}
