import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import publicService from '../services/publicService';
import { CourtNav, CourtFooter, CourtEmpty, CourtStatus, MatchCard } from '../components/PublicCourt';
import courtDate from '../utils/courtDate';
import '../styles/tournament-hub.css';

function TeamLogo({ team }) {
  const [failed, setFailed] = useState(false);
  const apiRoot = (import.meta.env.VITE_API_URL || 'http://127.0.0.1:8767/api').replace(/\/api\/?$/, '');
  const src = team.logo_url && (/^https?:\/\//.test(team.logo_url) ? team.logo_url : apiRoot + '/' + team.logo_url.replace(/^\//, ''));
  return <span className="hub-team-logo">{src && !failed ? <img src={src} alt={team.team_name+' logo'} onError={()=>setFailed(true)}/> : (team.team_name || 'Team').trim().split(/\s+/).slice(0,2).map(word=>word[0]).join('').toUpperCase()}</span>;
}
export default function PublicTournamentDetails() {
  const { id } = useParams();
  const [data,setData] = useState(null);
  const [tab,setTab] = useState('teams');
  const [loading,setLoading] = useState(true);
  const [error,setError] = useState('');
  const [attempt,setAttempt] = useState(0);
  const [selectedTeam,setSelectedTeam] = useState(null);
  const [scheduleView,setScheduleView] = useState('cards');
  const [teamFilter,setTeamFilter] = useState('all');
  useEffect(() => {
    let active=true;
    setLoading(true);setData(null);setError('');
    publicService.getTournament(id).then(value=>{if(active)setData(value);}).catch(err=>{if(active)setError(err.response?.status===404?'This tournament is not available.':'We could not load this tournament. Please try again.');}).finally(()=>{if(active)setLoading(false);});
    return()=>{active=false;};
  },[id,attempt]);
  const teams=data?.teams||[], schedule=data?.schedule||[], standings=data?.standings||[], leaders=data?.leaders||[], awards=data?.awards||[];
  const bracket=data?.bracket?.matches||[];
  const rounds=useMemo(()=>[...new Set((data?.bracket?.matches||[]).map(match=>match.round_number||1))].sort((a,b)=>Number(a)-Number(b)),[data]);
  const tournament=data?.tournament;
  const roundLabel=(round)=>{const position=rounds.indexOf(round),remaining=rounds.length-position;if(remaining===1)return 'Championship';if(remaining===2)return 'Semifinals';if(remaining===3)return 'Quarterfinals';return `Round ${round}`;};
  const tabCounts={teams:teams.length,schedule:schedule.length,bracket:bracket.length,rankings:standings.length,leaders:leaders.length};
  const selectedStanding=selectedTeam?standings.find(row=>Number(row.team_id)===Number(selectedTeam.id)):null;
  const filteredSchedule=schedule.filter(match=>teamFilter==='all'||String(match.team1_id)===teamFilter||String(match.team2_id)===teamFilter);
  const scheduleGroups=filteredSchedule.reduce((groups,match)=>{const key=match.scheduled_start_time?new Date(String(match.scheduled_start_time).replace(' ','T')).toLocaleDateString('en-PH',{weekday:'long',month:'long',day:'numeric'}):'To be announced';(groups[key]||=[]).push(match);return groups;},{});
  const tabs=[['teams','bi-people','Teams'],['schedule','bi-calendar-event','Game Schedules'],['bracket','bi-diagram-3','Bracket'],['rankings','bi-award','Rankings'],['leaders','bi-stars','Leaders']];
  return <div className="court-site"><CourtNav/>
    {loading?<main className="court-container court-section"><CourtEmpty>Loading tournament details…</CourtEmpty></main>:!tournament?<main className="court-container court-section"><div role="alert" className="court-error">{error||'Tournament not found.'}<button onClick={()=>setAttempt(value=>value+1)}>Try again</button></div><Link className="court-text-link" to="/sports">← Back to Game Center</Link></main>:<>
    <header className="hub-header"><div className="court-container"><Link to="/sports" className="hub-back"><i className="bi bi-arrow-left"/> Back to Game Center</Link><div className="hub-title-row"><div className="hub-title"><span className="court-kicker">{tournament.sport_name||'Basketball'} / Tournament hub</span><h1>{tournament.name}</h1><p>{tournament.description||'Follow the teams, matchups, and results throughout the competition.'}</p><div className="hub-meta"><CourtStatus status={tournament.status}/><span><i className="bi bi-calendar3"/> {courtDate(tournament.start_date)} – {courtDate(tournament.end_date)}</span><span><i className="bi bi-diagram-3"/> {String(tournament.format||'Tournament').replaceAll('_',' ')}</span></div></div><div className="hub-emblem" aria-hidden="true"><i className="bi bi-trophy"/><span>FULLCOURT</span><small>THE COMPETITION</small></div></div></div></header>
    <main className="court-container hub-main">
      <div className="hub-summary">{[['bi-people',teams.length,'Teams'],['bi-calendar-event',schedule.length,'Games'],['bi-check2-circle',schedule.filter(match=>match.status==='completed').length,'Completed'],['bi-broadcast',schedule.filter(match=>match.status==='in_progress').length,'Live now']].map(([icon,count,label])=><div key={label}><i className={'bi '+icon}/><span><b>{count}</b><small>{label}</small></span></div>)}</div>
      <div className="court-tabs hub-tabs" role="tablist" aria-label="Tournament sections">{tabs.map(([key,icon,label],index)=><button role="tab" key={key} id={'hub-tab-'+key} aria-controls={'hub-panel-'+key} aria-selected={tab===key} tabIndex={tab===key?0:-1} className={tab===key?'active':''} onClick={()=>setTab(key)} onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setTab(tabs[next][0]);document.getElementById('hub-tab-'+tabs[next][0])?.focus();}}><i className={'bi '+icon}/><span>{label}</span><b>{tabCounts[key]}</b></button>)}</div>
      <section role="tabpanel" id={'hub-panel-'+tab} aria-labelledby={'hub-tab-'+tab} className="hub-panel">
      <div className="hub-section-title"><h2>{{teams:'Meet the teams.',schedule:'The road to the final.',bracket:'Every round. Every matchup.',rankings:'The standings.',leaders:'Tournament leaders.'}[tab]}</h2><span>{tab==='teams'?teams.length+' competing teams':tab==='schedule'?schedule.length+' scheduled games':tab==='bracket'?rounds.length+' rounds':tab==='leaders'?leaders.length+' ranked players':'Tournament results'}</span></div>
      {tab==='teams'&&<div className="court-grid hub-teams-grid">{teams.length?teams.map((team,index)=><button type="button" className="hub-team-card" key={team.id} onClick={()=>setSelectedTeam(team)}><div className="hub-team-top"><span>TEAM {String(index+1).padStart(2,'0')}</span><CourtStatus status={team.status}/></div><TeamLogo team={team}/><h3>{team.team_name}</h3><div className="hub-team-coach"><i className="bi bi-person"/> Coach <strong>{team.coach_name||'To be announced'}</strong></div><div className="hub-team-bottom"><span><i className="bi bi-people"/> {team.player_count??0} verified players</span><span>Team profile <i className="bi bi-arrow-up-right"/></span></div></button>):<CourtEmpty>No registered teams yet. Teams will appear here once added.</CourtEmpty>}</div>}
      {tab==='schedule'&&<><div className="hub-schedule-tools"><label><i className="bi bi-people"/><span className="visually-hidden">Filter schedule by team</span><select value={teamFilter} onChange={event=>setTeamFilter(event.target.value)}><option value="all">All teams</option>{teams.map(team=><option key={team.id} value={team.id}>{team.team_name}</option>)}</select></label><div><button type="button" className={scheduleView==='cards'?'active':''} onClick={()=>setScheduleView('cards')}><i className="bi bi-grid"/> Cards</button><button type="button" className={scheduleView==='calendar'?'active':''} onClick={()=>setScheduleView('calendar')}><i className="bi bi-calendar3"/> By date</button></div></div>{filteredSchedule.length?(scheduleView==='cards'?<div className="court-grid hub-schedule-grid">{filteredSchedule.map((match,index)=><div className="hub-schedule-item" key={match.id}><span className="hub-game-number">GAME {String(index+1).padStart(2,'0')}</span><MatchCard match={{...match,tournament_id:id,tournament_name:match.stage_name||tournament.name,court_name:[match.venue_name,match.court_name].filter(Boolean).join(' • ')}}/></div>)}</div>:<div className="hub-date-schedule">{Object.entries(scheduleGroups).map(([date,games])=><section key={date}><header><i className="bi bi-calendar-event"/><div><h3>{date}</h3><span>{games.length} game{games.length===1?'':'s'}</span></div></header><div>{games.map(match=><MatchCard key={match.id} match={{...match,tournament_id:id,tournament_name:match.stage_name||tournament.name,court_name:[match.venue_name,match.court_name].filter(Boolean).join(' • ')}}/>)}</div></section>)}</div>):<CourtEmpty>{schedule.length?'No games found for this team.':'No games scheduled yet. Check back for the first fixtures.'}</CourtEmpty>}</>}
      {tab==='bracket'&&(rounds.length?<div className="hub-bracket">
        <div className="hub-bracket-head"><div><span>TOURNAMENT PATH</span><h3>Road to the championship</h3></div><p><i className="bi bi-info-circle"/> Swipe sideways on mobile to follow every round.</p></div>
        <div className="court-bracket-track">{rounds.map((round,roundIndex)=>{const roundMatches=bracket.filter(match=>(match.round_number||1)===round);return <section className={`court-round hub-round-${roundIndex+1}`} key={round} aria-label={roundLabel(round)}><header><span>{String(roundIndex+1).padStart(2,'0')}</span><div><h4>{roundLabel(round)}</h4><small>{roundMatches.length} matchup{roundMatches.length===1?'':'s'}</small></div>{roundIndex===rounds.length-1&&<i className="bi bi-trophy-fill"/>}</header><div className="hub-round-games">{roundMatches.map((match,index)=><article className="court-bracket-match" key={match.id}><div className="hub-match-top"><small>{match.stage_name||`Match ${match.match_number||match.id}`}</small><span>GAME {String(index+1).padStart(2,'0')}</span></div>{[['team1_name','team1_score','team1_id'],['team2_name','team2_score','team2_id']].map(([name,score,teamId],teamIndex)=>{const winner=match.winner_team_id&&Number(match.winner_team_id)===Number(match[teamId]);const teamName=match[name]||'To be determined';return <div className={`hub-bracket-team ${winner?'hub-winner':''}`} key={name}><span className="hub-bracket-seed">{match[teamId]?teamName.trim().split(/\s+/).slice(0,2).map(word=>word[0]).join('').toUpperCase():'?'}</span><span className="hub-bracket-name">{teamName}{winner&&<small>Winner</small>}</span><b>{['completed','in_progress'].includes(match.status)?match[score]??'–':'–'}</b>{winner&&<i className="bi bi-check-circle-fill"/>}{!winner&&teamIndex===0&&<span className="hub-team-divider"/>}</div>})}<div className="hub-match-footer"><CourtStatus status={match.status}/><span>{match.scheduled_start_time?courtDate(match.scheduled_start_time,true):'Schedule TBA'}</span></div></article>)}</div></section>})}</div>
        <div className="hub-bracket-legend"><span><i className="bi bi-circle-fill is-red"/> Winner / advancing</span><span><i className="bi bi-circle-fill is-gold"/> Championship round</span><span><i className="bi bi-dash-lg"/> Awaiting result</span></div>
      </div>:<CourtEmpty>The bracket has not been generated yet.</CourtEmpty>)}
      {tab==='rankings'&&<section className="hub-rankings-wrap">{standings.length?<><div className="hub-podium">{standings.slice(0,3).map((team,index)=><article key={team.team_id||index} className={`hub-podium-card place-${index+1}`}><span><i className={`bi ${index===0?'bi-trophy-fill':'bi-award-fill'}`}/></span><small>#{team.rank_position||index+1}</small><h3>{team.team_name}</h3><b>{team.tournament_points} PTS</b><p>{team.won} wins · {team.lost} losses</p></article>)}</div><div className="court-table-card"><div className="court-table-scroll"><table className="court-table hub-standings"><thead><tr><th>Rank</th><th>Team</th><th>Played</th><th>Won</th><th>Lost</th><th>Points</th></tr></thead><tbody>{standings.map((team,index)=><tr key={team.team_id||index}><td><span className={'hub-rank '+(Number(team.rank_position)===1?'first':'')}>{team.rank_position||'–'}</span></td><td><b>{team.team_name}</b></td><td>{team.played}</td><td>{team.won}</td><td>{team.lost}</td><td><strong className="hub-points">{team.tournament_points}</strong></td></tr>)}</tbody></table></div></div></>:<CourtEmpty>Rankings will appear after game results are recorded.</CourtEmpty>}</section>}
      {tab==='leaders'&&<div className="hub-leaders">{awards.length>0&&<section className="hub-awards"><div className="hub-leader-heading"><span>OFFICIAL HONORS</span><h3>Mythical Five &amp; Awards</h3></div><div>{awards.map((award,index)=><article key={`${award.name}-${index}`}><i className={award.name.startsWith('Mythical Five')?'bi bi-stars':'bi bi-trophy-fill'}/><span>{award.name}</span><h4>{award.full_name}</h4><p>#{award.jersey_number||'–'} · {award.position||'Player'} · {award.team_name||'Team'}</p></article>)}</div></section>}<section className="hub-player-leaders"><div className="hub-leader-heading"><span>TOURNAMENT-WIDE DATA</span><h3>Player leaderboard</h3><p>Statistics are based only on official recorded game events.</p></div>{leaders.length?<div className="court-table-scroll"><table className="court-table"><thead><tr><th>Rank</th><th>Player</th><th>PTS</th><th>REB</th><th>AST</th><th>STL</th><th>BLK</th></tr></thead><tbody>{leaders.map((player,index)=><tr key={`${player.user_id}-${player.team_name}`}><td><span className={'hub-rank '+(index===0?'first':'')}>{index+1}</span></td><td><b>#{player.jersey_number||'–'} {player.full_name}</b><small>{player.position||'Player'} · {player.team_name}</small></td><td><strong className="hub-points">{player.points}</strong></td><td>{player.rebounds}</td><td>{player.assists}</td><td>{player.steals}</td><td>{player.blocks}</td></tr>)}</tbody></table></div>:<CourtEmpty>Player leaders will appear after official statistics are recorded.</CourtEmpty>}</section></div>}
      </section>
      {selectedTeam&&<div className="hub-team-modal" role="dialog" aria-modal="true" aria-labelledby="hub-team-profile-title" onMouseDown={event=>{if(event.target===event.currentTarget)setSelectedTeam(null)}}><article><button type="button" className="hub-modal-close" aria-label="Close team profile" onClick={()=>setSelectedTeam(null)}><i className="bi bi-x-lg"/></button><div className="hub-modal-identity"><TeamLogo team={selectedTeam}/><div><span>OFFICIAL TEAM PROFILE</span><h2 id="hub-team-profile-title">{selectedTeam.team_name}</h2><p>Coach {selectedTeam.coach_name||'To be announced'}</p></div></div><div className="hub-team-profile-stats">{[['bi-people-fill',selectedTeam.player_count??0,'Verified players'],['bi-controller',selectedStanding?.played??0,'Games played'],['bi-trophy-fill',selectedStanding?.won??0,'Wins'],['bi-graph-up-arrow',selectedStanding?.tournament_points??0,'Tournament points']].map(([icon,value,label])=><div key={label}><i className={'bi '+icon}/><b>{value}</b><span>{label}</span></div>)}</div><div className="hub-team-profile-note"><i className="bi bi-shield-check"/><span><b>Public information only</b>Player contact details and private eligibility documents are protected.</span></div><button type="button" className="court-button" onClick={()=>{setSelectedTeam(null);setTab('schedule')}}>View game schedule <i className="bi bi-arrow-right"/></button></article></div>}
    </main></>}
    <CourtFooter/>
  </div>;
}
