import { useEffect, useRef, useState } from 'react';
import QRCode from 'qrcode';
import attendanceService from '../services/attendanceService';
import tournamentService from '../services/tournamentService';
import scheduleService from '../services/scheduleService';
import teamService from '../services/teamService';
import gameOperationsService from '../services/gameOperationsService';
import { useAuth } from '../hooks/useAuth';
import '../styles/qr-game-access.css';

const QUEUE_KEY='fullcourt_qr_offline_queue';
const managers=['platform_admin','admin','organization_admin','tournament_organizer'];
const readQueue=()=>{try{return JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]');}catch{return[];}};

const QRAttendanceView=()=>{
 const{user}=useAuth(),isManager=managers.includes(user?.role),isPlatformAdmin=['platform_admin','admin'].includes(user?.role),canOperate=['organization_admin','tournament_organizer'].includes(user?.role);
 const[tournaments,setTournaments]=useState([]),[selectedTournament,setSelectedTournament]=useState(''),[matches,setMatches]=useState([]),[teams,setTeams]=useState([]),[selectedMatch,setSelectedMatch]=useState(''),[selectedTeam,setSelectedTeam]=useState('');
 const[tab,setTab]=useState(isPlatformAdmin?'logs':canOperate?'scanner':'team'),[payload,setPayload]=useState(''),[teamQr,setTeamQr]=useState(null),[qrImage,setQrImage]=useState(''),[lineup,setLineup]=useState([]),[present,setPresent]=useState([]),[logs,setLogs]=useState([]),[queue,setQueue]=useState(readQueue),[message,setMessage]=useState(null),[cameraOn,setCameraOn]=useState(false),[syncing,setSyncing]=useState(false);
 const videoRef=useRef(null),streamRef=useRef(null),scanTimer=useRef(null);

 useEffect(()=>{tournamentService.getTournaments().then(result=>{const rows=result.tournaments||[];setTournaments(rows);if(rows[0])setSelectedTournament(String(rows[0].id));});},[]);
 useEffect(()=>{if(!selectedTournament)return;Promise.all([scheduleService.getSchedule(selectedTournament),teamService.getTeamsByTournament(selectedTournament)]).then(([gameRows,teamRows])=>{setMatches(gameRows);setTeams(teamRows);if(gameRows[0])setSelectedMatch(String(gameRows[0].id));if(teamRows[0])setSelectedTeam(String(teamRows[0].id));});},[selectedTournament]);
 useEffect(()=>{if(!selectedMatch)return;gameOperationsService.lineup(selectedMatch).then(rows=>{setLineup(rows);setPresent(rows.filter(row=>Number(row.is_present)!==0).map(row=>Number(row.team_player_id)));}).catch(()=>setLineup([]));attendanceService.getMatchAttendance(selectedMatch).then(setLogs).catch(()=>setLogs([]));},[selectedMatch]);
 useEffect(()=>{if(!selectedTeam)return;attendanceService.getTeamQR(selectedTeam).then(async team=>{setTeamQr(team);setQrImage(await QRCode.toDataURL(team.qr_payload,{width:360,margin:2,color:{dark:'#18181b',light:'#ffffff'}}));}).catch(()=>{setTeamQr(null);setQrImage('');});},[selectedTeam]);
 useEffect(()=>()=>{if(streamRef.current)streamRef.current.getTracks().forEach(track=>track.stop());if(scanTimer.current)clearInterval(scanTimer.current);},[]);

 const notify=(type,text)=>setMessage({type,text});
 const saveQueue=items=>{setQueue(items);localStorage.setItem(QUEUE_KEY,JSON.stringify(items));};
 const teamIdFromPayload=value=>{const match=value.match(/^FULLCOURT:TEAM:(\d+):/);return match?Number(match[1]):0;};
 const submitTeam=async(value=payload,playerIds=present,syncUuid=crypto.randomUUID())=>{
   if(!selectedMatch||!value)return notify('danger','Select a game and scan a team QR code.');
   const teamId=teamIdFromPayload(value);if(!teamId)return notify('danger','The scanned code is not a FullCourt team QR.');
   const eligibleForTeam=lineup.filter(row=>Number(row.team_id)===teamId).map(row=>Number(row.team_player_id));const selected=playerIds.filter(id=>eligibleForTeam.includes(Number(id)));
   const item={matchId:Number(selectedMatch),qrPayload:value,playerIds:selected,syncUuid,queuedAt:new Date().toISOString()};
   if(!navigator.onLine){saveQueue([...queue,item]);setPayload('');return notify('warning','Saved offline. This check-in will be verified when connection returns.');}
   try{const response=await attendanceService.scanQR(item.matchId,item.qrPayload,item.playerIds,item.syncUuid);notify('success',response.message);setPayload('');setLogs(await attendanceService.getMatchAttendance(item.matchId));}
   catch(error){if(!error.response){saveQueue([...queue,item]);notify('warning','Network unavailable. Check-in saved to the offline queue.');}else notify('danger',error.response.data?.message||'Team check-in failed.');}
 };
 const syncQueue=async()=>{if(!navigator.onLine)return notify('warning','Internet connection is still unavailable.');setSyncing(true);const remaining=[];let synced=0;for(const item of queue){try{await attendanceService.scanQR(item.matchId,item.qrPayload,item.playerIds,item.syncUuid);synced++;}catch(error){if(!error.response)remaining.push(item);}}saveQueue(remaining);setSyncing(false);notify('success',`${synced} offline check-in${synced===1?'':'s'} synchronized.`);if(selectedMatch)setLogs(await attendanceService.getMatchAttendance(selectedMatch));};
 const validateOfficial=async()=>{try{const response=await attendanceService.validateOfficialQR(Number(selectedMatch),payload);notify('success',`${response.message} ${response.data?.access?.official_name} — ${response.data?.access?.assignment_role}`);setPayload('');}catch(error){notify('danger',error.response?.data?.message||'Official access denied.');}};
 const startCamera=async()=>{if(!('BarcodeDetector'in window))return notify('warning','Camera QR detection is not supported by this browser. Use the manual field instead.');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});streamRef.current=stream;setCameraOn(true);setTimeout(()=>{videoRef.current.srcObject=stream;videoRef.current.play();const detector=new window.BarcodeDetector({formats:['qr_code']});scanTimer.current=setInterval(async()=>{try{const codes=await detector.detect(videoRef.current);if(codes[0]?.rawValue){setPayload(codes[0].rawValue);stopCamera();notify('success','QR captured. Review the roster, then confirm.');}}catch{/* wait for next frame */}},500);},0);}catch{notify('danger','Camera permission was denied or no camera is available.');}};
 const stopCamera=()=>{if(scanTimer.current)clearInterval(scanTimer.current);scanTimer.current=null;if(streamRef.current)streamRef.current.getTracks().forEach(track=>track.stop());streamRef.current=null;setCameraOn(false);};
 const downloadQr=()=>{if(!qrImage)return;const link=document.createElement('a');link.href=qrImage;link.download=`fullcourt-${teamQr.team_name.replace(/\s+/g,'-').toLowerCase()}-qr.png`;link.click();};
 const scannedTeam=teamIdFromPayload(payload);

 return <div className="container-fluid p-0 qr-access-page">
  <div className="qr-access-hero"><div><span className="qr-access-eyebrow">{isPlatformAdmin?'ACCESS OVERSIGHT':canOperate?'GAME-DAY ACCESS':'TEAM PASS'}</span><h3 className="fw-bold mb-1"><i className="bi bi-qr-code-scan text-evsu-primary me-2"/>{isPlatformAdmin?'QR Access Oversight':'QR Game Access'}</h3><p className="text-muted small mb-0">{isPlatformAdmin?'Monitor verified team arrivals, official access, and offline synchronization.':'Printed team passes, offline attendance, and one-time official game access'}</p></div><div className="qr-connection-panel"><span className={`qr-online-dot ${navigator.onLine?'online':'offline'}`}/><div><b>{navigator.onLine?'System online':'Offline mode'}</b><small>{queue.length?`${queue.length} check-in${queue.length===1?'':'s'} waiting to sync`:'Attendance queue is clear'}</small></div>{queue.length>0&&canOperate&&<button className="btn btn-warning btn-sm" onClick={syncQueue} disabled={syncing}><i className="bi bi-cloud-arrow-up me-1"/>{syncing?'Syncing…':`Sync ${queue.length}`}</button>}</div></div>
  <section className="qr-access-stats"><article><i className="bi bi-trophy"/><div><small>Tournaments</small><strong>{tournaments.length}</strong></div></article><article><i className="bi bi-calendar2-check"/><div><small>Scheduled games</small><strong>{matches.length}</strong></div></article><article><i className="bi bi-people"/><div><small>Registered teams</small><strong>{teams.length}</strong></div></article><article><i className="bi bi-patch-check"/><div><small>Verified check-ins</small><strong>{logs.length}</strong></div></article></section>
  {isPlatformAdmin&&<div className="qr-oversight-notice"><i className="bi bi-shield-lock-fill"/><div><b>Administrator oversight mode</b><span>Organizers operate scanners and issue team passes. Administrators monitor verified game-access records.</span></div></div>}
  {message&&<div className={`alert alert-${message.type}`}>{message.text}</div>}
  <div className="nav nav-pills qr-access-tabs">{canOperate&&<button className={`nav-link ${tab==='scanner'?'active':''}`} onClick={()=>setTab('scanner')}><i className="bi bi-camera me-2"/>Court Scanner</button>}{!isPlatformAdmin&&<button className={`nav-link ${tab==='team'?'active':''}`} onClick={()=>setTab('team')}><i className="bi bi-printer me-2"/>Printable Team QR</button>}{isManager&&<button className={`nav-link ${tab==='logs'?'active':''}`} onClick={()=>setTab('logs')}><i className="bi bi-list-check me-2"/>Check-in Log <span>{logs.length}</span></button>}</div>
  <div className="qr-game-picker"><div><i className="bi bi-1-circle-fill"/><label><span>Competition</span><select className="form-select" value={selectedTournament} onChange={event=>setSelectedTournament(event.target.value)}>{tournaments.map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select></label></div><div><i className="bi bi-2-circle-fill"/><label><span>Scheduled game</span><select className="form-select" value={selectedMatch} onChange={event=>setSelectedMatch(event.target.value)}>{matches.map(row=><option value={row.id} key={row.id}>{row.stage_name}: {row.team1_name||'TBD'} vs {row.team2_name||'TBD'}</option>)}</select></label></div></div>
  {tab==='scanner'&&<div className="row g-4"><div className="col-lg-5"><div className="card-custom p-4 h-100"><h5 className="fw-bold">Scan or paste QR</h5><p className="text-muted small">Camera scanning needs one organizer device only.</p>{cameraOn?<div><video ref={videoRef} className="w-100 rounded-3 bg-dark mb-3" playsInline muted/><button className="btn btn-outline-danger w-100" onClick={stopCamera}>Stop camera</button></div>:<button className="btn btn-dark w-100 mb-3" onClick={startCamera}><i className="bi bi-camera-fill me-2"/>Open camera scanner</button>}<label className="form-label small fw-bold">Scanner data / manual fallback</label><textarea className="form-control font-monospace" rows="4" value={payload} onChange={event=>setPayload(event.target.value.trim())} placeholder="FULLCOURT:TEAM:… or FULLCOURT:OFFICIAL:…"/><div className="d-grid gap-2 mt-3"><button className="btn btn-evsu" onClick={()=>submitTeam()} disabled={!payload.startsWith('FULLCOURT:TEAM:')}>Verify team check-in</button><button className="btn btn-outline-warning" onClick={validateOfficial} disabled={!payload.startsWith('FULLCOURT:OFFICIAL:')}>Validate official access</button></div></div></div><div className="col-lg-7"><div className="card-custom p-4 h-100"><h5 className="fw-bold">Present players</h5><p className="text-muted small">After scanning the team QR, select the players who arrived. Players do not need phones or internet.</p>{!scannedTeam?<div className="text-center text-muted py-5"><i className="bi bi-people fs-1 d-block mb-2"/>Scan a team QR to load its eligible roster.</div>:<div className="row g-2">{lineup.filter(row=>Number(row.team_id)===scannedTeam).map(row=><div className="col-md-6" key={row.team_player_id}><label className="d-flex align-items-center gap-3 p-3 border rounded-3"><input type="checkbox" className="form-check-input m-0" checked={present.includes(Number(row.team_player_id))} onChange={event=>setPresent(current=>event.target.checked?[...new Set([...current,Number(row.team_player_id)])]:current.filter(id=>id!==Number(row.team_player_id)))}/><span><b>#{row.jersey_number||'—'} {row.full_name}</b><small className="d-block text-muted">{row.position||'Player'}</small></span></label></div>)}</div>}</div></div></div>}
  {tab==='team'&&<div className="row g-4"><div className="col-lg-5"><div className="card-custom p-4"><label className="form-label fw-bold">Team</label><select className="form-select" value={selectedTeam} onChange={event=>setSelectedTeam(event.target.value)}>{teams.map(row=><option value={row.id} key={row.id}>{row.team_name}</option>)}</select><div className="alert alert-info small mt-3 mb-0">Download or print this before game day. Players do not need Wi-Fi; the organizer scans one team pass.</div></div></div><div className="col-lg-7"><div className="card-custom p-4 text-center">{qrImage?<><span className="badge bg-dark mb-3">OFFICIAL TEAM PASS</span><h4 className="fw-bold">{teamQr?.team_name}</h4><p className="text-muted">{teamQr?.tournament_name}</p><img src={qrImage} alt={`${teamQr?.team_name} QR code`} className="img-fluid rounded-3 border" style={{maxWidth:320}}/><div><button className="btn btn-evsu mt-3" onClick={downloadQr}><i className="bi bi-download me-2"/>Download printable QR</button></div></>:<p className="text-muted py-5">Select a team to generate its pass.</p>}</div></div></div>}
  {tab==='logs'&&<div className="qr-log-panel"><div className="qr-log-head"><div><span>GAME ACCESS RECORDS</span><h5>Verified courtside arrivals</h5></div><span className="badge rounded-pill text-bg-success">{logs.length} verified</span></div><div className="table-responsive"><table className="table table-modern align-middle mb-0"><thead><tr><th>Check-in time</th><th>Team</th><th>Verified by</th><th>Access status</th></tr></thead><tbody>{logs.length===0?<tr><td colSpan="4"><div className="qr-empty"><i className="bi bi-qr-code"/><b>No verified check-ins</b><span>Organizer-scanned team passes for this game will appear here.</span></div></td></tr>:logs.map(row=><tr key={row.id}><td>{new Date(row.scanned_at).toLocaleString()}</td><td className="fw-bold">{row.team_name}</td><td>{row.scanned_by_name}</td><td><span className="badge bg-success"><i className="bi bi-check2-circle me-1"/>Verified</span></td></tr>)}</tbody></table></div></div>}
 </div>;
};
export default QRAttendanceView;
