import {useEffect,useMemo,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useAuth} from '../hooks/useAuth';
import authService from '../services/authService';

const steps=['Account type','Profile details','Verification','Security'];
const Register=()=>{
 const [step,setStep]=useState(1),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[show,setShow]=useState(false),[codeSeconds,setCodeSeconds]=useState(0);
 const [form,setForm]=useState({playing_position:'Not Sure',height_cm:'',team_name:'',coaching_experience:'',organization_name:'',organization_address:'',role:'player',full_name:'',birth_date:'',age:'',address:'',email:'',department_course:'',year_level:'',phone_number:'',verification_code:'',password:'',confirmPassword:''});
 const {register}=useAuth(),nav=useNavigate();
 const set=event=>{const {name,value}=event.target;if(name==='birth_date'){const today=new Date(),birth=new Date(`${value}T00:00:00`);let age=today.getFullYear()-birth.getFullYear();const month=today.getMonth()-birth.getMonth();if(month<0||(month===0&&today.getDate()<birth.getDate()))age--;setForm({...form,birth_date:value,age:value&&age>=0?String(age):''});return;}setForm({...form,[name]:value});};
 const rules=useMemo(()=>[{text:'At least 8 characters',ok:form.password.length>=8},{text:'One uppercase letter',ok:/[A-Z]/.test(form.password)},{text:'One number',ok:/\d/.test(form.password)},{text:'One special character',ok:/[^A-Za-z0-9]/.test(form.password)}],[form.password]);
 useEffect(()=>{if(codeSeconds<=0)return;const timer=setInterval(()=>setCodeSeconds(value=>Math.max(0,value-1)),1000);return()=>clearInterval(timer);},[codeSeconds]);
 const timerText=`${String(Math.floor(codeSeconds/60)).padStart(2,'0')}:${String(codeSeconds%60).padStart(2,'0')}`;
 const isMobileContact=/^(09\d{9}|\+639\d{9})$/.test(form.email.replace(/[\s-]/g,''));
 const requestCode=async()=>{setError('');if(form.role==='organization_admin'&&(!form.organization_name.trim()||!form.organization_address.trim()))return setError('Organization name and address are required.');if(form.role==='player'&&form.height_cm!==''&&(!Number.isFinite(Number(form.height_cm))||Number(form.height_cm)<=0||Number(form.height_cm)>300))return setError('Enter a valid height in centimeters (up to 300).');if(form.role==='coach'&&form.coaching_experience!==''&&(!/^\d+$/.test(form.coaching_experience)||Number(form.coaching_experience)>Number(form.age)))return setError('Coaching experience must be a whole number between 0 and your age.');if(!form.full_name||!form.birth_date||!form.address||!form.email)return setError('Full name, date of birth, email or mobile number, and complete address are required.');if(!form.age||Number(form.age)<1||Number(form.age)>120)return setError('Enter a valid date of birth.');const contact=form.email.replace(/[\s-]/g,'');if(!/^\S+@\S+\.\S+$/.test(contact)&&!(/^(09\d{9}|\+639\d{9})$/.test(contact)))return setError('Enter a valid email address or Philippine mobile number.');setLoading(true);try{const response=await authService.requestEmailCode(contact);setMessage(response.message+(response.data?.development_code?` Development code: ${response.data.development_code}`:''));setCodeSeconds(180);setStep(3);}catch(e){setError(e.response?.data?.message||e.message);}finally{setLoading(false);}};
 const next=()=>step===1?setStep(2):requestCode();
 const resend=async()=>{if(codeSeconds>0)return;setMessage('');await requestCode();};
 const verify=async()=>{setError('');if(form.verification_code.length!==6)return setError('Enter the complete 6-digit code.');setLoading(true);try{const response=await authService.verifyRegistrationCode(form.email,form.verification_code);setMessage(response.message);setStep(4);}catch(e){setError(e.response?.data?.message||'The code is invalid or expired.');}finally{setLoading(false);}};
 const submit=async event=>{event.preventDefault();setError('');if(!rules.every(rule=>rule.ok))return setError('Please meet all password requirements.');if(form.password!==form.confirmPassword)return setError('Passwords do not match.');setLoading(true);try{await register(form);setStep(5);setTimeout(()=>nav('/login'),1800);}catch(e){setError(e.response?.data?.message||e.message);}finally{setLoading(false);}};
 return <div className="register-wrap">
  <Link to="/login" className="auth-back d-inline-flex mb-3"><i className="bi bi-arrow-left"/> Return to login</Link>
  <div className="auth-page-heading register-heading mb-4"><span className="auth-page-icon"><i className="bi bi-person-plus-fill"/></span><span className="auth-page-kicker">Your next chapter starts here</span><h2>Get in the game.</h2><p>Create your FullCourt account. Start by choosing your role.</p></div>
  {step<=4&&<div className="stepper">{steps.map((label,index)=><div className={`step ${index+1<step?'done':''} ${index+1===step?'active':''}`} key={label}><span>{index+1<step?<i className="bi bi-check-lg"/>:index+1}</span><small>{label}</small></div>)}</div>}
  {error&&<div className="form-alert error" role="alert"><i className="bi bi-exclamation-circle"/>{error}</div>}{message&&step===3&&<div className="form-alert success"><i className="bi bi-envelope-check"/>{message}</div>}
  {step===1&&<section className="form-step"><h4>How will you use FullCourt?</h4><p>Officials and statisticians are assigned by an organization administrator.</p><div className="role-grid" role="group" aria-label="Choose your account role"><button type="button" aria-pressed={form.role==='player'} className={form.role==='player'?'selected':''} onClick={()=>setForm({...form,role:'player'})}><i className="bi bi-person-fill"/><b>Player</b><small>Schedules, stats, history, and awards</small></button><button type="button" aria-pressed={form.role==='coach'} className={form.role==='coach'?'selected':''} onClick={()=>setForm({...form,role:'coach'})}><i className="bi bi-clipboard2-pulse"/><b>Coach</b><small>Rosters, eligibility, and lineups</small></button><button type="button" aria-pressed={form.role==='organization_admin'} className={form.role==='organization_admin'?'selected':''} onClick={()=>setForm({...form,role:'organization_admin'})}><i className="bi bi-trophy-fill"/><b>Competition Organizer</b><small>Apply for an organization and run competitions</small></button></div><button className="btn btn-neon w-100 mt-4" onClick={next}>Continue <i className="bi bi-arrow-right"/></button></section>}
  {step===2&&<section className="form-step"><h4>Your profile</h4><p>Use accurate details for invitations and eligibility review.</p><div className="form-grid"><div className="field full"><label>Full Name</label><input className="modern-input" name="full_name" placeholder="Juan Dela Cruz" value={form.full_name} onChange={set}/></div><div className="field"><label htmlFor="register-birth-date">Date of Birth</label><input id="register-birth-date" className="modern-input" name="birth_date" type="date" max={new Date().toISOString().split('T')[0]} value={form.birth_date} onChange={set}/></div><div className="field"><label htmlFor="register-age">Age</label><input id="register-age" className="modern-input" name="age" type="number" placeholder="Calculated automatically" value={form.age} readOnly aria-readonly="true"/></div><div className="field full"><label>Email Address or Mobile Number</label><input className="modern-input" name="email" type="text" placeholder="name@gmail.com or 09XXXXXXXXX" value={form.email} onChange={set}/></div><div className="field full"><label>Complete Address</label><textarea className="modern-input registration-address" name="address" rows="2" placeholder="Enter your complete address" value={form.address} onChange={set}/></div>
{form.role==='player'&&<>
<div className="field"><label htmlFor="playing-position">Playing Position</label><select id="playing-position" className="modern-input" name="playing_position" value={form.playing_position} onChange={set}>{['Not Sure','Point Guard','Shooting Guard','Small Forward','Power Forward','Center'].map(position=><option key={position}>{position}</option>)}</select></div>
<div className="field"><label htmlFor="player-height">Height (cm, optional)</label><input id="player-height" className="modern-input" type="number" min="1" max="300" step="0.01" name="height_cm" placeholder="e.g. 175" value={form.height_cm} onChange={set}/></div>
</>}
{form.role==='coach'&&<>
<div className="field"><label htmlFor="coach-team">Team Name (optional)</label><input id="coach-team" className="modern-input" name="team_name" maxLength="150" value={form.team_name} onChange={set}/><small className="text-muted">You can create or join a team after signing in.</small></div>
<div className="field"><label htmlFor="coach-experience">Coaching Experience (years, optional)</label><input id="coach-experience" className="modern-input" name="coaching_experience" type="number" min="0" max={form.age||120} step="1" placeholder="0 for beginners" value={form.coaching_experience} onChange={set}/></div>
</>}
{form.role==='organization_admin'&&<>
<div className="field full"><label htmlFor="org-name">Organization Name</label><input id="org-name" className="modern-input" name="organization_name" maxLength="150" value={form.organization_name} onChange={set}/></div>
<div className="field full"><label htmlFor="org-address">Organization Address</label><textarea id="org-address" className="modern-input" name="organization_address" rows="2" maxLength="1000" value={form.organization_address} onChange={set}/></div>
<div className="field full"><small className="text-muted">Your organization requires admin approval before you can manage competitions.</small></div>
</>}
</div><div className="step-actions"><button className="btn btn-soft" onClick={()=>setStep(1)}>Back</button><button className="btn btn-neon" onClick={next} disabled={loading}>{loading?'Sending code…':'Send verification code'}</button></div></section>}
  {step===3&&<section className="form-step verify-step"><span className="mail-illustration"><i className={`bi ${isMobileContact?'bi-phone':'bi-envelope-paper-heart'}`}/></span><h4>{isMobileContact?'Check your phone':'Check your email'}</h4><p className="text-muted small">We sent a 6-digit code to {form.email}.</p><div className={`small fw-semibold mb-3 ${codeSeconds>0?'text-success':'text-danger'}`}><i className="bi bi-clock me-2"/>{codeSeconds>0?`Code expires in ${timerText}`:'Code expired. Request a new code.'}</div><input aria-label="Verification code" className="modern-input code-input" inputMode="numeric" maxLength="6" placeholder="000000" value={form.verification_code} onChange={event=>setForm({...form,verification_code:event.target.value.replace(/\D/g,'')})}/><button type="button" className="btn btn-outline-secondary w-100 mt-3" onClick={resend} disabled={loading||codeSeconds>0}>Resend code</button><div className="step-actions"><button className="btn btn-soft" onClick={()=>setStep(2)}>Back</button><button className="btn btn-neon" onClick={verify} disabled={loading||codeSeconds===0}>Verify and Continue</button></div></section>}
  {step===4&&<form className="form-step" onSubmit={submit}><h4>Secure your account</h4><div className="password-field"><input className="modern-input" name="password" type={show?'text':'password'} placeholder="Create a password" value={form.password} onChange={set}/><button type="button" onClick={()=>setShow(!show)}><i className={`bi bi-eye${show?'-slash':''}`}/></button></div><div className="password-rules">{rules.map(rule=><span className={rule.ok?'ok':''} key={rule.text}><i className={`bi bi-${rule.ok?'check-circle-fill':'circle'}`}/>{rule.text}</span>)}</div><label>Confirm password</label><input className="modern-input" name="confirmPassword" type="password" value={form.confirmPassword} onChange={set}/><div className="step-actions"><button type="button" className="btn btn-soft" onClick={()=>setStep(3)}>Back</button><button className="btn btn-neon" disabled={loading}>{loading?'Creating…':'Create account'}</button></div></form>}
  {step===5&&<section className="form-step text-center"><div className="success-check"><i className="bi bi-check-lg"/></div><h3>Welcome to FullCourt!</h3><p>Your account is ready. Redirecting you to sign in…</p></section>}
  <div className="text-center mt-3"><span className="text-muted small">Already registered? </span><Link className="auth-link small" to="/login">Sign in</Link></div>
 </div>;
};
export default Register;
