<?php

declare(strict_types=1);

$source = $argv[1] ?? __DIR__ . '/../FullCourt_Database.sql';
$target = $argv[2] ?? __DIR__ . '/../FullCourt_PostgreSQL.sql';
$sql = file_get_contents($source);
if ($sql === false) {
    fwrite(STDERR, "Unable to read {$source}.\n");
    exit(1);
}

preg_match_all('/CREATE TABLE `([^`]+)` \((.*?)\) ENGINE=.*?;/s', $sql, $tableMatches, PREG_SET_ORDER);
if ($tableMatches === []) {
    fwrite(STDERR, "No MySQL table definitions were found.\n");
    exit(1);
}

$tables = [];
$foreignKeys = [];
$indexes = [];
$identityTables = [];

foreach ($tableMatches as $tableMatch) {
    $table = $tableMatch[1];
    $lines = preg_split('/\R/', trim($tableMatch[2]));
    $definitions = [];

    foreach ($lines as $rawLine) {
        $line = trim($rawLine);
        $line = rtrim($line, ',');
        if ($line === '') {
            continue;
        }

        if (str_starts_with($line, 'CONSTRAINT ')) {
            $foreignKeys[] = 'ALTER TABLE ' . $table . ' ADD ' . convertIdentifiers($line) . ';';
            continue;
        }

        if (preg_match('/^KEY `([^`]+)` \((.+)\)$/', $line, $keyMatch)) {
            $indexes[] = 'CREATE INDEX IF NOT EXISTS ' . safeName($table . '_' . $keyMatch[1])
                . ' ON ' . $table . ' (' . convertIdentifiers($keyMatch[2]) . ');';
            continue;
        }

        if (preg_match('/^UNIQUE KEY `([^`]+)` \((.+)\)$/', $line, $keyMatch)) {
            $definitions[] = 'CONSTRAINT ' . safeName($table . '_' . $keyMatch[1])
                . ' UNIQUE (' . convertIdentifiers($keyMatch[2]) . ')';
            continue;
        }

        if (str_contains($line, 'AUTO_INCREMENT')) {
            $identityTables[] = $table;
        }

        $definitions[] = convertDefinition($line);
    }

    $tables[] = "CREATE TABLE IF NOT EXISTS {$table} (\n  "
        . implode(",\n  ", $definitions) . "\n);";
}

preg_match_all('/INSERT INTO `([^`]+)` VALUES (.*?);\R/s', $sql, $insertMatches, PREG_SET_ORDER);
$inserts = [];
foreach ($insertMatches as $insertMatch) {
    $values = str_replace("\\'", "''", $insertMatch[2]);
    $values = str_replace('\\"', '"', $values);
    $inserts[] = 'INSERT INTO ' . $insertMatch[1] . ' VALUES ' . $values . ';';
}

$sequences = [];
foreach (array_unique($identityTables) as $table) {
    $sequences[] = "SELECT setval(pg_get_serial_sequence('{$table}', 'id'), "
        . "GREATEST(COALESCE((SELECT MAX(id) FROM {$table}), 1), 1), "
        . "EXISTS(SELECT 1 FROM {$table}));";
}

$header = <<<'SQL'
-- FullCourt PostgreSQL schema and demo data
-- Generated from FullCourt_Database.sql for Supabase PostgreSQL.
-- Run in a new Supabase project using the SQL Editor.

BEGIN;
SET client_encoding = 'UTF8';
SET timezone = 'UTC';

SQL;

$output = $header
    . implode("\n\n", $tables)
    . "\n\n-- Demo and current application data\n"
    . implode("\n", $inserts)
    . "\n\n-- Foreign keys are added after data loading to support dump ordering.\n"
    . implode("\n", $foreignKeys)
    . "\n\n-- Secondary indexes\n"
    . implode("\n", array_unique($indexes))
    . "\n\n-- Advance identity sequences after importing explicit IDs.\n"
    . implode("\n", $sequences)
    . "\n\nCOMMIT;\n";

if (file_put_contents($target, $output) === false) {
    fwrite(STDERR, "Unable to write {$target}.\n");
    exit(1);
}

fwrite(STDOUT, 'Converted ' . count($tables) . ' tables and ' . count($inserts) . " data blocks.\n");

function convertDefinition(string $line): string
{
    $line = convertIdentifiers($line);
    $line = preg_replace('/\benum\((?:[^\']|\'(?:\'\'|[^\'])*\')*\)/i', 'text', $line) ?? $line;
    $line = preg_replace('/\bbigint\(\d+\)/i', 'bigint', $line) ?? $line;
    $line = preg_replace('/\bint\(\d+\)/i', 'integer', $line) ?? $line;
    $line = preg_replace('/\btinyint\(\d+\)/i', 'smallint', $line) ?? $line;
    $line = preg_replace('/\b(?:longtext|mediumtext)\b/i', 'text', $line) ?? $line;
    $line = preg_replace('/\bdatetime\b/i', 'timestamp', $line) ?? $line;
    $line = preg_replace('/\s+CHARACTER SET\s+\w+/i', '', $line) ?? $line;
    $line = preg_replace('/\s+COLLATE\s+\w+/i', '', $line) ?? $line;
    $line = preg_replace('/\s+CHECK\s*\(json_valid\([^)]*\)\)/i', '', $line) ?? $line;
    $line = str_ireplace('AUTO_INCREMENT', 'GENERATED BY DEFAULT AS IDENTITY', $line);
    $line = preg_replace('/current_timestamp\(\)/i', 'CURRENT_TIMESTAMP', $line) ?? $line;
    $line = preg_replace('/\s+ON UPDATE CURRENT_TIMESTAMP/i', '', $line) ?? $line;
    return $line;
}

function convertIdentifiers(string $value): string
{
    return str_replace('`', '', $value);
}

function safeName(string $value): string
{
    $name = strtolower(preg_replace('/[^a-zA-Z0-9_]+/', '_', $value) ?? $value);
    if (strlen($name) <= 63) {
        return $name;
    }
    return substr($name, 0, 54) . '_' . substr(hash('sha256', $name), 0, 8);
}
